# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Vagrantfile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shamsate <shamsate@student.1337.ma>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/11 15:42:31 by shamsate          #+#    #+#              #
#    Updated: 2026/06/11 15:44:35 by shamsate         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box Ubuntu hautement optimisée, légère et stable (fournie par Bento Chef)
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.boot_timeout = 600
  
  config.ssh.insert_key = false

  # -------------------------------------------------------------
  # MACHINE 1 : SERVEUR (Master)
  # -------------------------------------------------------------
  config.vm.define "shamsateS" do |server|
    server.vm.hostname = "shamsateS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 1024 Mo de RAM pour le Master (recommandé pour K3s)
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/k3s-server.sh"
  end

  # -------------------------------------------------------------
  # MACHINE 2 : SERVERWORKER (Agent)
  # -------------------------------------------------------------
  config.vm.define "shamsateSW" do |agent|
    agent.vm.hostname = "shamsateSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  
      vb.cpus = 1
    end

    agent.vm.provision "shell", path: "scripts/k3s-worker.sh"
  end
end
