Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false

  config.vm.define "shamsateS" do |server|
    server.vm.hostname = "shamsateS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true
    server.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end

    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
